---
title: "Tcell Flow: sgSCR Opt Replating Exp 2"
author: "Kate Johnson"
date: "2024-09-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# libraries ----
```{r}
library(tidyverse)
library(fs)
library(cowplot)
library(ggpubr) # for stats
library(readxl)
```

# directories ----
```{r}
wd = getwd()
input_dir = fs::path(wd, "../../../../input/data")
output_dir = fs::path(wd, "../../../../output/2024/2024_11/20241108/20241108_coculture")
```

# load data ----
```{r}
dat = read_xlsx(path(input_dir, "2024/2024_11/20241108_coculture/20241108_coculture_celldose_opt_gluOE.xlsx")) 
```


#bar plots-opt exp------------
glu-tRNA OE
```{r}
plot_me = dat %>%
          select(-Sample) %>%
          filter((Experiment == "Glu_tRNA_OE" &#| 
                   # (Treatment != "LSG_MOI1" &
                    # Target == "sgSCR" & BMDC_number == "25k")) & 
                   !(grepl("mChe|GFP", Target)) &
                   Target != "NA"),
                 grepl("TTC-2|SCR", Target) & 
                   Treatment %in% c("OVA", "S", "G")) %>%
          mutate(Treatment = gsub("_MOI.*", "", Treatment)) %>%
          group_by(Target, Treatment) %>%
          mutate(n_live = n(),
                 avg_live = mean(Live),
                 se_live = sd(Live)/sqrt(n_live),
                 avg_prolif = mean(Proliferated),
                 n_prolif = n(),
                 se_prolif = sd(Proliferated)/sqrt(n_prolif)) %>%
          mutate(Treatment = factor(Treatment, 
                              levels = c("OVA", "L", "S", "S_MOI10", "G",
                                         "LS", "LS_MOI10", "LSG",
                                         "LSG_MOI1", "LSG_MOI10")),
                 BMDC_number = factor(BMDC_number, 
                                      levels = c("10k","25k",
                                                 "50k", "100k")),
                 Target = factor(Target, levels = c("sgSCR", "pLX_GFP",
                                                    "pLX_mCherry",
                                                    "CTC-1.1",
                                                    "TTC-1.3",
                                                    "TTC-2.1"))
                 ) %>%
          arrange(Treatment) %>%
          mutate(Sample = str_c(Target, "_", Treatment))

plot_me = plot_me %>%
          mutate(Sample = factor(Sample, levels = unique(Sample)))

means = plot_me %>% 
        select(Treatment, Target, Sample,
               avg_live, se_live, avg_prolif, se_prolif) %>% 
        unique()


#plot
p<-ggplot(plot_me, 
       aes(x = Sample,
           y = Proliferated,
           fill = Treatment)) +
  geom_col(data = means,
           aes(y = avg_prolif), , 
            color = "black") +
  geom_point(size = 1) +
  geom_errorbar(data= means,
                aes(ymin = avg_prolif - se_prolif,
                    ymax = avg_prolif + se_prolif,
                    x = Sample, width = 0.5),
                inherit.aes=F) +
  #geom_hline(data = means %>% filter(Treatment == "OVA"), 
          #   aes(yintercept = 18.9), linetype = 2) +
  scale_fill_manual(values = c("OVA" = "white",
                                "L" =  "#B9CEE6",
                                 "S" = "#8C9FCA", 
                                 "G" = "#707FA1",
                                 "LS" = "#68C3A5",
                                "LSG" = "#F68064"))+
  labs(x = NULL, y = "% OTII Proliferation") +
  facet_wrap(~Treatment, scales = "free_x", nrow =1) +
  theme(axis.text.x =element_text(angle =45,hjust =1),
        text = element_text(size=16),
        legend.position = "none") 

p
save_plot(path(output_dir, "Glu_OE/Glu_OE_TTC-2_Percent_Proliferated.pdf"), p,
          base_aspect_ratio = 2)



p<-ggplot(plot_me, 
       aes(x = Sample,
           y = Live,
           fill = Treatment)) +
  geom_col(data = means,
           aes(y = avg_live), , 
            color = "black") +
  geom_point(size = 1) +
  geom_errorbar(data= means,
                aes(ymin = avg_live - se_live,
                    ymax = avg_live + se_live,
                    x = Sample, width = 0.5),
                inherit.aes=F) +
  #geom_hline(data = means %>% filter(Treatment == "OVA"), 
             #aes(yintercept = 79.2), linetype = 2) +
  scale_fill_manual(values = c("OVA" = "white",
                                "L" =  "#B9CEE6",
                                 "S" = "#8C9FCA", 
                                 "G" = "#707FA1",
                                 "LS" = "#68C3A5",
                                "LSG" = "#F68064"))+
  labs(x = NULL, y = "% Live OTII Cells") +
  facet_wrap(~Treatment, scales = "free_x", nrow =1) +
  theme(axis.text.x =element_text(angle =45,hjust =1),
        text = element_text(size=16),
        legend.position = "none")
p
save_plot(path(output_dir, "Glu_OE/Glu_OE_TTC-2_Tcell_Percent_Live.pdf"), p,
          base_aspect_ratio = 2)

```

cell dose optimization
```{r}
plot_me = dat %>%
          select(-Sample) %>%
          filter(Experiment == "celldose_opt") %>%
          group_by(Target, Treatment, BMDC_number) %>%
          mutate(n_live = n(),
                 avg_live = mean(Live),
                 se_live = sd(Live)/sqrt(n_live),
                 avg_prolif = mean(Proliferated),
                 n_prolif = n(),
                 se_prolif = sd(Proliferated)/sqrt(n_prolif)) %>%
          mutate(Treatment = factor(Treatment, 
                              levels = c("OVA", "L", "S", "S_MOI10", "G",
                                         "LS", "LS_MOI10", "LSG",
                                         "LSG_MOI1", "LSG_MOI10")),
                 BMDC_number = factor(BMDC_number, 
                                      levels = c("10k","25k",
                                                 "50k", "100k")),
                 Target = factor(Target, levels = c("sgSCR", "pLX_GFP",
                                                    "pLX_mCherry",
                                                    "CTC-1.1",
                                                    "TTC-1.3",
                                                    "TTC-2.1"))
                 ) %>%
          arrange(Treatment) %>%
          mutate(Sample = str_c(Treatment))

plot_me = plot_me %>%
          mutate(Sample = factor(Sample, levels = unique(Sample)))

means = plot_me %>% 
        select(Treatment, Target, Sample, BMDC_number,
               avg_live, se_live, avg_prolif, se_prolif) %>% 
        unique()


#plot
p<-ggplot(plot_me, 
       aes(x = Sample,
           y = Proliferated,
           fill = Treatment)) +
  geom_col(data = means,
           aes(y = avg_prolif), , 
            color = "black") +
  geom_point(size = 1) +
  geom_errorbar(data= means,
                aes(ymin = avg_prolif - se_prolif,
                    ymax = avg_prolif + se_prolif,
                    x = Sample, width = 0.5),
                inherit.aes=F) +
  #geom_hline(data = means %>% filter(Treatment == "OVA"), 
          #   aes(yintercept = 18.9), linetype = 2) +
  scale_fill_manual(values = c("OVA" = "white",
                                "L" =  "#B9CEE6",
                                 "S_MOI10" = "#8C9FCA", 
                                 "G" = "#707FA1",
                                 "LS_MOI10" = "#68C3A5",
                                "LSG_MOI10" = "#F68064",
                               "LSG_MOI1" = "#FBCCC1"
                               ))+
  labs(x = NULL, y = "% OTII Proliferation") +
  facet_wrap(~BMDC_number, scales = "fixed", nrow=1) +
  theme(axis.text.x =element_text(angle =45,hjust =1),
        text = element_text(size=16),
        legend.position = "none") 

p
save_plot(path(output_dir, "celldose_opt/celldose_opt_Percent_Proliferated.pdf"), p,
          base_aspect_ratio = 2.5)



p<-ggplot(plot_me, 
       aes(x = Sample,
           y = Live,
           fill = Treatment)) +
  geom_col(data = means,
           aes(y = avg_live), , 
            color = "black") +
  geom_point(size = 1) +
  geom_errorbar(data= means,
                aes(ymin = avg_live - se_live,
                    ymax = avg_live + se_live,
                    x = Sample, width = 0.5),
                inherit.aes=F) +
  #geom_hline(data = means %>% filter(Treatment == "OVA"), 
             #aes(yintercept = 79.2), linetype = 2) +
  scale_fill_manual(values = c("OVA" = "white",
                                "L" =  "#B9CEE6",
                                 "S_MOI10" = "#8C9FCA", 
                                 "G" = "#707FA1",
                                 "LS_MOI10" = "#68C3A5",
                                "LSG_MOI10" = "#F68064",
                               "LSG_MOI1" = "#FBCCC1"))+
  labs(x = NULL, y = "% Live OTII Cells") +
  facet_wrap(~BMDC_number, scales = "fixed", nrow =1) +
  theme(axis.text.x =element_text(angle =45,hjust =1),
        text = element_text(size=16),
        legend.position = "none")
p
save_plot(path(output_dir, "celldose_opt/celldose_opt_Tcell_Percent_Live.pdf"), p,
          base_aspect_ratio = 2.5)

```

