---
title: "b16 tumor exp analysis"
author: "Kate Johnson"
date: "2024-11-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# libraries ----
```{r}
library(tidyverse)
library(fs)
library(cowplot)
library(ggpubr) # for stats
library(circlize) #for colorRamp2
library(RcppGSL) # colNorm() function
library(ComplexHeatmap)
library(ggtext) #for element_markdown()
library(readxl)
library(monochromeR) 

```
#set theme
```{r}
# Plot settings ----
#compress PDFs
tools::compactPDF('mypdfs/',  gs_quality='screen')
###PLOTTING THEME ###
theme_update(#text = element_text(size = rel(3)),
             legend.title = element_text(size = rel(0.8)),
             legend.key.size = unit(.09, 'inches'),
             legend.text = element_text(size = rel(0.8)),
             panel.background = element_rect(fill = "white",
                                             colour = "black"),
             axis.line = element_blank(),
             plot.title = element_text(size = rel(1), 
                                      face= "bold", hjust=0.5),
             plot.margin = unit(c(0.08, 0.1, 0.01, 0.05), "inches"),
             strip.background = element_rect(linewidth=0.35, color="black"),
             legend.key = element_rect(colour = NA, fill = NA)) #trbl
```

# directories ----
```{r}
wd = getwd()
input_dir = fs::path(wd, "../../../../../../Data/b16_tumor")
output_dir = fs::path(wd, "../../../output/b16_tumors")
```


# load data ----
```{r}
dat = read_excel(path(input_dir, "20241213_b16_tumor_exp5.xlsx"), sheet = "measurement_log") 

```

# plot ----
```{r}
exp = "5"
day = 28
#my_comps = list("SCR-OVA-LSG" = "OVA|SCR-LSG", "B16-OVA" = "OVA|B16",
 #               "B16-SCR-LSG" = "SCR-LSG|B16",
  #              "SCR-OVA-Glsg2" = "SCR-OVA|Gls_g2", 
   #             "SCR-LSG-Glsg2" = "SCR-LSG|Gls_g2", 
    #            "SCR-OVA-Glsg3" = "OVA|Gls_g3",
     #           "SCR-LSG-Glsg3" = "SCR-LSG|Gls_g3",
      #         "SCR-OVA-Eprsg3" = "SCR-OVA|Eprs_g3", 
       #        "SCR-LSG-Eprsg3" = "SCR-LSG|Eprs_g3", 
        #        "SCR-OVA-Eprsg4" = "OVA|Eprs_g4",
         #      "SCR-LSG-Eprsg4" = "SCR-LSG|Eprs_g4")

my_comps = list("SCR-OVA-LSG" = "OVA|SCR-LSG", "B16-OVA" = "OVA|B16",
                "B16-SCR-LSG" = "SCR-LSG|B16")

for(i in (1:length(my_comps))){#calc tumor volume (.5 * D * d^2) D = Y, d = X
  plot_me = dat %>% 
          select(Mouse_ID,  Day, Group, Cage_card, Condition, X_Dimension, Y_Dimension,
                 calc_vol) %>%
          filter((grepl(my_comps[[i]], Condition))) %>%
          mutate(Minor = as.numeric(X_Dimension) < as.numeric(Y_Dimension),
                 D1 = ifelse(Minor, as.numeric(Y_Dimension), as.numeric(X_Dimension)),
                 d1 = ifelse(Minor, as.numeric(X_Dimension), as.numeric(Y_Dimension)),
                 D = as.numeric(Y_Dimension),
                 d = as.numeric(X_Dimension),
                 Mouse_ID = str_c(Group, "_", Cage_card, "M", Mouse_ID),
                 Day = as.numeric(gsub("d", "", Day)),
                 Volume = 0.5*D1*(d1)^2,
                 Condition = factor(Condition, 
                                    levels = c("B16_only","sgSCR-OVA", "sgSCR-LSG",
                                    "sgGls_g2-LSG", "sgGls_g3-LSG",
                                    "sgEprs_g3-LSG", "sgEprs_g4-LSG"))) %>%
          filter(Day <= day) 


#calc averages
means = plot_me %>%
        select(Group, Condition, Volume, Mouse_ID, Day) %>%
        group_by(Group, Condition, Day) %>%
        summarise(n = n(),
                  mean = mean(Volume, na.rm=T),
                  se = sd(Volume)/sqrt(n)) %>%
        filter(!is.na(se))

p_base <-ggplot(plot_me, aes(x = Day, y = Volume, color = Condition))+
         scale_color_manual(values = c("sgSCR-OVA" ="black",
                             "B16_only" = "grey",
                            "sgSCR-LSG" = "#F68064",
                            "sgGls_g2-LSG" = "#BD5353",#"#F08686",
                         "sgGls_g3-LSG" = "#8E3E3E",#"#ED6868","#E31A1C",
                          "sgEprs_g3-LSG" = "#A6DFF7",
                          "sgEprs_g4-LSG" ="#A5C7DE")) +
         labs(x = "Time (Days)", y = "Tumor Volume (mm<sup>3</sup>)", 
              title = str_c("KJ B16-TE-", exp)) +
         theme(axis.title.y = element_markdown(),
               legend.key.size = unit(.25, 'inches'))
   
p_indiv<-p_base +
         geom_line(aes ( linetype = as.character(Cage_card),
           group = Mouse_ID), alpha = 0.4, linewidth = 1) 

p_avg <-p_base +
        geom_line(data = means, aes(x = Day, y =mean), linewidth = 1.75) +
        geom_point(data = means, aes(x = Day, y = mean))

p_indiv_avg<-p_indiv +
       geom_line(data = means, aes(x = Day, y =mean), linewidth = 1.75) +
       geom_point(data = means, aes(x = Day, y = mean)) 

p_avg_error = p_avg +
              geom_errorbar(data =means, aes(x = Day, ymin = mean-se, ymax = mean+se,
                                 color  = Condition), 
                            width = 0.3, linewidth = 1.75, inherit.aes = F) 
p_everything = p_indiv_avg +
               geom_errorbar(data =means, aes(x = Day, ymin = mean-se, ymax = mean+se,
                                 color  = Condition), 
                            width = 0.3, linewidth = 1.75, inherit.aes = F)
p_list<-list("p_indiv" = p_indiv,
          "p_indiv_avg" = p_indiv_avg,
          "p_avg_error" = p_avg_error,
          "p_everything" = p_everything)

for(j in (1:length(p_list))){
  save_plot(path(output_dir, str_c("TE",exp, "/d", 
                 as.character(day),
                 "/d", as.character(day),"_bycage/",
                 names(my_comps)[[i]], "/tumor_vol_TE", exp,"-",names(my_comps)[[i]],
                names(p_list)[j], ".pdf")),
                p_list[[j]], base_aspect_ratio =1.4)
  }
}

```

