---
title: "b16 tumor exp analysis"
author: "Kate Johnson"
date: "2024-11-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# libraries ----
```{r}
library(tidyverse)
library(fs)
library(cowplot)
library(ggpubr) # for stats
library(circlize) #for colorRamp2
library(RcppGSL) # colNorm() function
library(ComplexHeatmap)
library(ggtext) #for element_markdown()
library(readxl)
```
#set theme
```{r}
# Plot settings ----
#compress PDFs
tools::compactPDF('mypdfs/',  gs_quality='screen')
###PLOTTING THEME ###
theme_update(#text = element_text(size = rel(3)),
             legend.title = element_text(size = rel(0.8)),
             legend.key.size = unit(.09, 'inches'),
             legend.text = element_text(size = rel(0.8)),
             panel.background = element_rect(fill = "white",
                                             colour = "black"),
             axis.line = element_blank(),
             plot.title = element_text(size = rel(1), 
                                      face= "bold", hjust=0.5),
             plot.margin = unit(c(0.08, 0.1, 0.01, 0.05), "inches"),
             strip.background = element_rect(linewidth=0.35, color="black"),
             legend.key = element_rect(colour = NA, fill = NA)) #trbl
```

# directories ----
```{r}
wd = getwd()
input_dir = fs::path(wd, "../../../input/data/b16_tumors")
output_dir = fs::path(wd, "../../../output/b16_tumors/surya_data/full_table")
```


# load data ----
```{r, warning =FALSE}
dat = read_excel(path(input_dir, "b16_raw_all.xlsx"), sheet = "B16_all") 

```

# plot ----
```{r}
#calc tumor volume (.5 * D * d^2) D = Y, d = X
dat_filt = dat %>% 
            filter(grepl("Ova|OVA|ZScG|Ctrl|B16", Group)) %>%
            filter((!grepl("_noOva|Proph|LO|HI|_sc_|_ip_|PD1|NoDC|No_DC|B16", Group))) %>%
            filter(Experiment %in% c("8","10","16"))

plot_me = dat_filt %>%
          mutate(Mouse_ID_Exp2 = str_c(Mouse_ID, "_E", Experiment),
                 Day = as.numeric(Day),
                 Outliers = ifelse(Outliers == 0, F, T),
                 Volume = ifelse((Volume== "NA" & `1000mm3` == "0" & 
                                    Died == "0" & Day < 15 ) | 
                                   (Volume == "NA" & Experiment == "16" & Day < 20), 0,
                                 Volume),
                 Volume = as.numeric(Volume)) %>%
          select(-c(Mouse_ID_exp, D,d,Genoype, Weight, Notes, `...18`)) %>%
          filter(Day < 23) %>%
          filter(!(Experiment == "16" & Day == 17 & Treatment == "LScG" & 
                     Mouse_ID_Exp2 == "6_E16")) 

#calc averages
means = plot_me %>%
        group_by(Day, Treatment, Group) %>%
        summarise(n = n(),
                  mean = mean(Volume, na.rm=T),
                  se = sd(Volume)/sqrt(n))  

p<-ggplot(plot_me, aes(x = Day, y = Volume, color = Treatment))+
  geom_line(aes(group = str_c(Mouse_ID_Exp2), linetype = Outliers),
            alpha = 0.4, linewidth = 1) +
  #geom_line(data = means, aes(x = Day, y =mean), linewidth = 1.75) +
  #geom_point(data = means, aes(x = Day, y = mean)) +
  #geom_errorbar(data =means, aes(x = Day, ymin = mean-se, ymax = mean+se,
           #                     color  = Treatment), 
           #     width = 0.3, linewidth = 1.75, inherit.aes = F) +
  scale_color_manual(values = c("black","#F68064","#F68064", "orange")) +
  labs(x = "Time (Days)", y = "Tumor Volume (mm<sup>3</sup>)", 
       title = "Surya B16 Data: T5-T19 Aggregated - Excluded Mice in Dashed Lines") +
  ylim(0,1500)+
  xlim(7,21)+
  #facet_wrap(~Experiment, scales = "free_x", nrow=1) +
  theme(axis.title.y = element_markdown(),
        legend.position = "right")

p

save_plot(path(output_dir, "ZSG_5-16_aggregated.pdf"),p, base_aspect_ratio = 1.25 )

```

