---
title: "b16 tumor exp analysis"
author: "Kate Johnson"
date: "2024-11-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# libraries ----
```{r}
library(tidyverse)
library(fs)
library(cowplot)
library(ggpubr) # for stats
library(circlize) #for colorRamp2
library(RcppGSL) # colNorm() function
library(ComplexHeatmap)
library(ggtext) #for element_markdown()
library(readxl)
```
#set theme
```{r}
# Plot settings ----
#compress PDFs
tools::compactPDF('mypdfs/',  gs_quality='screen')
###PLOTTING THEME ###
theme_update(#text = element_text(size = rel(3)),
             legend.title = element_text(size = rel(0.8)),
             legend.key.size = unit(.09, 'inches'),
             legend.text = element_text(size = rel(0.8)),
             panel.background = element_rect(fill = "white",
                                             colour = "black"),
             axis.line = element_blank(),
             plot.title = element_text(size = rel(1), 
                                      face= "bold", hjust=0.5),
             plot.margin = unit(c(0.08, 0.1, 0.01, 0.05), "inches"),
             strip.background = element_rect(linewidth=0.35, color="black"),
             legend.key = element_rect(colour = NA, fill = NA)) #trbl
```

# directories ----
```{r}
wd = getwd()
input_dir = fs::path(wd, "../../../../../../Data/b16_tumor")
output_dir = fs::path(wd, "../../../output/b16_tumors/surya_data")
```


# load data ----
```{r}
dat = read_excel(path(input_dir, "surya_b16_data.xlsx"), sheet = "Sheet1") 

```

# plot ----
```{r}
#calc tumor volume (.5 * D * d^2) D = Y, d = X
dat_pivot = dat %>% 
            mutate_all(~as.character(.)) %>%
            pivot_longer(cols = c(contains("Condition"), contains("Mouse")),
                         names_to = "Exp_Name", values_to = "value" ) %>%
            separate(Exp_Name, into = c("Experiment", "Name"), sep = "_") %>%
            pivot_wider(names_from = "Name", values_from = "value") %>%
            pivot_longer(cols = -c("Experiment", "Condition", "Mouse"),
                         names_to = "Exp_time", values_to = "Volume") %>%
            separate(Exp_time, into = c("Exp", "Time"), sep = "_") %>%
            filter(Exp == Experiment) %>%
            filter(!is.na(Condition)) %>%
            filter(!(grepl("IC|RH|i.p.|s.c.", Condition))) %>%
            mutate(Time = as.numeric(gsub("d|D", "", Time)),
                   Volume = as.numeric(Volume),
                   Mouse = str_c(Condition, "_M", Mouse),
                   Route = ifelse(grepl("DC", Condition), "DC vaccine", 
                                  ifelse(grepl("i.p.", Condition), "soluble vaccine (i.p.)",
                                         ifelse(grepl("s.c.", Condition), 
                                                "soluble vaccine (s.c.)", "other")))) %>%
                   #Condition = factor(Condition, levels = c("DC+25 Ova only", 
                                               #             "DC+LScG", "Ova-i.p.", 
                                                    #        "LScG-i.p.", "Ova- s.c.", 
                                                          #  "LScG-s.c."))) %>%
             #filter(Time <= 21 & Time > 0) %>%
            select(-Exp) %>%
            mutate()

plot_me = dat_pivot %>% 
          #filter(Experiment %in% c(,"T29")) %>%
          filter(Condition == "DC+25 Ova only" | Condition == "DC+LScG")

#calc averages
means = plot_me %>%
        group_by(Condition, Route, Time) %>%
        summarise(n = n(),
                  mean = mean(Volume, na.rm=T),
                  se = sd(Volume)/sqrt(n)) #%>%
        filter(!(is.na(se)) | Experiment=="T21"| Experiment == "T19")


p<-ggplot(plot_me, aes(x = Time, y = Volume, color = Condition))+
  geom_line( aes(group = str_c(Mouse, Experiment)), alpha = 0.4, linewidth = 1) +
  geom_line(data = means, aes(x = Time, y =mean), linewidth = 1.75) +
  geom_point(data = means, aes(x = Time, y = mean)) +
  geom_errorbar(data =means, aes(x = Time, ymin = mean-se, ymax = mean+se,
                                color  = Condition), 
                width = 0.3, linewidth = 1.75, inherit.aes = F) +
  ylim(0,1500) +
  xlim(0,21) +
  scale_color_manual(values = c("black","#F68064" )) +
  labs(x = "Time (Days)", y = "Tumor Volume (mm<sup>3</sup>)", 
       title = "Surya B16 Data - T20-29") +
  #facet_wrap(~Experiment, scales = "free_x") +
  theme(axis.title.y = element_markdown(),
        legend.position = "right")

p

save_plot(path(output_dir, "LSG_T18-29_fixed_indiv_aggregated.pdf"),p, base_aspect_ratio = 1.5 )

```

