---
title: "Glu_inhibitor_coculture"
author: "Kate Johnson"
date: "2024-07-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# libraries ----
```{r}
library(tidyverse)
library(fs)
library(cowplot)
library(ggpubr) # for stats
```

# directories ----
```{r}
wd = getwd()
input_dir = fs::path(wd, "../../input/data")
output_dir = fs::path(wd, "../../output/2024/2024_07/20240715/Glu_inhib_coculture3")
```

# load data ----
```{r}
dat = read.csv(path(input_dir, "2024/2024_07/20240715_glu_inhib_coculture_3.csv")) 
```

#test plotting
```{r}
plot_me = dat %>% 
          pivot_longer(cols = c("Proliferated", "Live"), 
                       names_to = "metric",
                       values_to = "value") %>%
          filter(Drug %in% c("None", "Glutamate")) %>%
          filter(Treatment == "LSG+OVA")

#artificially add controls as 0 point for all curves
#controls = dat %>%

p<-ggplot(plot_me, aes(x = Concentration, 
                y = value,
                color = Treatment, 
                alpha = as.character(Plate))) +
    geom_point(size = 3) +
    scale_alpha_manual(values = c(0.5,1)) +
    scale_color_manual(values = c("OVA" = "black",
                                  "LSG+OVA" = "#F68064")) +
    #ylim(50,95) +
    scale_x_continuous(trans = scales::pseudo_log_trans(sigma = 0.00001)) +
    labs(x = str_c("Concentration (uM)"), 
         y = "Percent",
         title = "Glutamate Spike-In") +
    facet_wrap(~metric, scales = "fixed") +
    theme(legend.position = "none",
          text = element_text(size = 14),
          axis.text.x = element_text(angle=45, hjust = 1),
          plot.title = element_text(hjust =0.5, size = 12))

save_plot(path(output_dir, "Glutamate_zoom.pdf"), p, base_aspect_ratio = 2)

```


#plots of everything at once
```{r}
plot_me = dat %>% 
          #filter(Treatment == "LSG+OVA") %>%
          #filter low prolif bc dead
          #%>%
          #factor drug list
          mutate(Drug = factor(Drug, levels = c("None", "DMSO", "Glutamate", "AAA",
                                               "Erastin", "DL-AP4", "CPCCOEt",
                                               "MPEP", "Cerestat", "D-AP5",
                                               "DNQX")))

p<-ggplot(plot_me, aes(x = Concentration, 
                y = Proliferated,
                color = Treatment, 
                alpha = as.character(Rep))) +
    geom_point(size = 3) +
    scale_alpha_manual(values = c(0.5,0.75,1)) +
    scale_color_manual(values = c("OVA" = "black",
                                  "LSG+OVA" = "#F68064")) +
    #ylim(50,95) +
    scale_x_continuous(trans = scales::pseudo_log_trans(sigma = 0.0001)) +
    labs(x = str_c("Concentration (DMSO: % v/v; else uM)"), 
         y = "% Proliferated") +
    facet_wrap(~Drug, scales = "free_x", nrow =1) +
    theme(legend.position = "none",
          text = element_text(size = 14),
          axis.text.x = element_text(angle=45, hjust = 1, size = 10),
          plot.title = element_text(hjust =0.5, size = 12))

save_plot(path(output_dir, "All_drugs_proliferated.pdf"), p, base_aspect_ratio = 4)

```


#bar plot

```{r}
plot_me = dat %>% 
          filter(Treatment == "LSG+OVA") %>%
          #filter low prolif bc dead
          filter(!((Drug == "Cerestat" & Concentration > 90) |
                     (Drug == "Erastin" & Concentration > 40) |
                     (Drug == "DMSO" & Concentration > 0.4)|
                     (Drug == "MPEP" & Concentration > 100)|
                     (Drug == "DNQX" & Concentration > 100))) %>%
          #factor drug list
          mutate(Drug = factor(Drug, levels = c("None", "DMSO", "Glutamate", "AAA",
                                               "Erastin", "DL-AP4", "CPCCOEt",
                                               "MPEP", "Cerestat", "D-AP5",
                                               "DNQX"))) %>%
          group_by(Drug) %>%
          mutate(Max = max(Concentration)) %>%
          ungroup() %>%
          filter(Concentration == Max) %>%
          group_by(Drug) %>%
          mutate(avg = mean(Proliferated),
                 se = sd(Proliferated)/sqrt(2),
                 Drug2 = ifelse(Drug == "None","None",
                                str_c(Drug, " (", round(Concentration,2), Unit, ")"))) %>%
          arrange(Drug)

plot_me2 = plot_me %>% mutate(Drug2 = factor(Drug2, levels = unique(plot_me$Drug2)))
means = plot_me2 %>% select(Drug, Drug2, avg) %>% unique()

p<-ggplot(plot_me2, 
       aes(x = Drug2, 
           y = Proliferated)) +
  geom_col(data = means, aes(y = avg), fill = "#F68064", color = "black") +
  geom_point() +
  geom_hline(aes(yintercept = 70.56), linetype =2) +
  labs(x = NULL, y = "% Proliferated") +
  theme(axis.text.x =element_text(angle =45,hjust =1))


save_plot(path(output_dir, "all_drugs_barplot_CPCCOEt_high.pdf"), p)

stat_compare_means(mapping = aes(x = Drug2, y = Proliferated),
                     method = "wilcox",
                     ref.group = "None",
                     label = "p.signif")
p
```


#barplots of everyting
```{r}
plot_me = dat %>%
          #factor drug list
          mutate(#Drug = ifelse(Drug == "None" & 
                       #          Treatment == "OVA", "None \n(Untreated)",
                           #   ifelse(Drug == "None" & Treatment == "LSG+OVA",
                            #         "None \n(Treated)", Drug)),
                 Drug = factor(Drug, levels = c("None", # \n(Untreated)", "None \n(Treated)",
                                                "DMSO", "Glutamate", "AAA",
                                               "Erastin", "DL-AP4", "CPCCOEt",
                                               "MPEP", "Cerestat", "D-AP5",
                                               "DNQX")),
                 Treatment = factor(Treatment, levels = c("OVA", "LSG+OVA"))) %>%
          group_by(Drug, Concentration, Unit, Dilution, Treatment) %>%
          #mutate(Max = max(Concentration)) %>%
          #ungroup() %>%
          #filter(Concentration == Max) %>%
          #group_by(Drug) %>%
          mutate(avg = mean(Live),
                 se = sd(Live)/sqrt(3),
                 Drug2 = ifelse(grepl("None", Drug),"None",
                                str_c(Drug, " (", round(Concentration,2), Unit, ")"))) %>%
          arrange(Drug, desc(Concentration))

plot_me2 = plot_me %>% mutate(Drug2 = factor(Drug2, levels = unique(plot_me$Drug2)))
means = plot_me2 %>% select(Drug, Drug2, avg) %>% unique()

p<-ggplot(plot_me2, 
       aes(x = Drug2, 
           y = Live)) +
  geom_col(data = means, aes(y = avg,
                             alpha = as.character(Dilution),
                             fill = Treatment), 
                             position = position_dodge2(width =1,preserve = "total"), 
            color = "black") +
  geom_point(#aes(#alpha = as.character(Dilution),
                  #fill = Treatment), 
    position = position_dodge2(width = 1, preserve = "total"),
    size = 1) +
  #geom_hline(#data = plot_me2 %>% filter(Drug2 == "None (Treated)"),
            # aes(yintercept = 14.4), linetype =2) +
  scale_fill_manual(values = c("OVA" = "white",
                                "LSG+OVA" = "#F68064")) +
  scale_alpha_manual(values = c("3" = 0.3, "2" = 0.6, "1" = 1)) +
  facet_wrap(~Drug, scales="free_x", nrow=1) +
  labs(x = NULL, y = "% Live") +
  theme(axis.text.x =element_text(angle =45,hjust =1)) +
  guides(alpha = "none" )


save_plot(path(output_dir, "LIVE_all_drugs_barplot_v2.pdf"), p,
          base_aspect_ratio = 3)

p
```

